name: first workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
     
      - name: Set up JDK 8  
        uses: actions/setup-java@v3  
        with:  
          distribution: 'temurin'  # Alternatives: 'zulu', 'adopt', etc.
          java-version: '8'  
          cache: 'maven'  # Enables dependency caching for faster builds  

      - name: Build with Maven  
        run: mvn clean package
      - name: Download the code from artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .
  
    
