name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "good mrng"
      - name: print greet
        run: echo "good evng"  
    
